// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPURqlPAh5ufHqleJYXRcnAM_Xief4Ri8',
    appId: '1:669737508551:web:c969e4dbd03d23549228e2',
    messagingSenderId: '669737508551',
    projectId: 'penny-1baa7',
    authDomain: 'penny-1baa7.firebaseapp.com',
    storageBucket: 'penny-1baa7.appspot.com',
    measurementId: 'G-W5KB7THVJ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpqWPBhV1t9DPnZkLARadq_0C-apRoPaI',
    appId: '1:669737508551:android:1a30cb7148ecb98f9228e2',
    messagingSenderId: '669737508551',
    projectId: 'penny-1baa7',
    storageBucket: 'penny-1baa7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYydwwktjKqafyJGAgr9SoGt61gu8GYYM',
    appId: '1:669737508551:ios:6d970cd25b92b2949228e2',
    messagingSenderId: '669737508551',
    projectId: 'penny-1baa7',
    storageBucket: 'penny-1baa7.appspot.com',
    androidClientId: '669737508551-ekl6f1gs1tfgonk6jcg1veeqa2b3qmch.apps.googleusercontent.com',
    iosClientId: '669737508551-hjlj2c0aeut5ibfm1v5ldrehbf9csf56.apps.googleusercontent.com',
    iosBundleId: 'dev.ezzy.penny',
  );

}